import type { Metadata } from 'next';
import { locationSeoData } from './locationdata';

export const aboutSeo: Metadata = {
  title: 'About BRL RENEWABLE ENERGIES PVT LTD | Our Mission to Power India with Solar Energy',
  description: 'Learn about BRL RENEWABLE ENERGIES PVT LTD, a leading solar EPC company in India dedicated to providing high-quality, affordable solar energy solutions for a sustainable future.',
  keywords: [
    ...(locationSeoData.keywords as string[]),
    'reliable solar installers in Chennai',
    'trusted solar brand in Telangana',
    'trusted solar brand in Delhi',
    'biggest solar companies in Tamil Nadu',
    'top solar EPC company in Ahmedabad',
    'reliable solar installers in Delhi NCR',
    'biggest solar companies in UP',
    'top 10 solar companies',
    'trusted solar brand in UP',
    'reliable solar installers in Hyderabad',
    'reliable solar installers in Indore',
    'reliable solar installers in Jaipur',
    'trusted solar brand in Gujarat',
    'top solar EPC company in Lucknow',
    'solar plant engineers',
    'top solar EPC company in Surat',
    'biggest solar companies in Telangana',
    'biggest solar companies in Rajasthan',
    'trusted solar brand in Kerala',
    'solar panel manufacturers',
    'top solar EPC company in Bangalore',
    'trusted solar brand in Maharashtra',
    'reliable solar installers in Mumbai',
    'sustainable business solar',
    'biggest solar companies in Gujarat',
    'top solar EPC company in Hyderabad',
    'renewable energy companies',
    'biggest solar companies in Maharashtra',
    'top solar EPC company in Delhi NCR',
    'biggest solar companies in MP',
    'trusted solar brand in Tamil Nadu',
    'top solar EPC company in Pune',
    'trusted solar brand in Punjab',
    'solar energy visionaries',
    'green energy startups india',
    'biggest solar companies in Kerala',
    'reliable solar installers in Pune',
    'reliable solar installers in Surat',
    'trusted solar brand in MP',
    'BRL RENEWABLE ENERGIES PVT LTD company profile',
    'biggest solar companies in Delhi',
    'top solar EPC company in Mumbai',
    'trusted solar brand in Rajasthan',
    'biggest solar companies in Haryana',
    'reliable solar installers in Lucknow',
    'biggest solar companies in Karnataka',
    'reliable solar installers in Bangalore',
    'biggest solar companies in Punjab',
    'solar project developers',
    'top solar EPC company in Chennai',
    'about BRL RENEWABLE ENERGIES PVT LTD',
    'top solar EPC company in Nagpur',
    'reliable solar installers in Ahmedabad',
    'top solar EPC company in Indore',
    'trusted solar brand in Haryana',
    'top solar EPC company in Jaipur',
    'trusted solar brand in Karnataka',
    'solar epc contractors in india',
    'reliable solar installers in Nagpur',
    'why choose solar energy 0',
    'why choose solar energy 1',
    'why choose solar energy 2',
    'why choose solar energy 3',
    'why choose solar energy 4',
    'why choose solar energy 5',
    'why choose solar energy 6',
    'why choose solar energy 7',
    'why choose solar energy 8',
    'why choose solar energy 9',
    'why choose solar energy 10',
    'why choose solar energy 11',
    'why choose solar energy 12',
    'why choose solar energy 13',
    'why choose solar energy 14',
    'why choose solar energy 15',
    'why choose solar energy 16',
    'why choose solar energy 17',
    'why choose solar energy 18',
    'why choose solar energy 19',
    'why choose solar energy 20',
    'why choose solar energy 21',
    'why choose solar energy 22',
    'why choose solar energy 23',
    'why choose solar energy 24',
    'why choose solar energy 25',
    'why choose solar energy 26',
    'why choose solar energy 27',
    'why choose solar energy 28',
    'why choose solar energy 29',
    'why choose solar energy 30',
    'why choose solar energy 31',
    'why choose solar energy 32',
    'why choose solar energy 33',
    'why choose solar energy 34',
    'why choose solar energy 35',
    'why choose solar energy 36',
    'why choose solar energy 37',
    'why choose solar energy 38',
    'why choose solar energy 39',
    'why choose solar energy 40',
    'why choose solar energy 41',
    'why choose solar energy 42',
    'why choose solar energy 43',
    'why choose solar energy 44',
    'why choose solar energy 45',
    'why choose solar energy 46',
    'why choose solar energy 47',
    'why choose solar energy 48',
    'why choose solar energy 49',
    'why choose solar energy 50',
    'why choose solar energy 51',
    'why choose solar energy 52',
    'why choose solar energy 53',
    'why choose solar energy 54',
    'why choose solar energy 55',
    'why choose solar energy 56',
    'why choose solar energy 57',
    'why choose solar energy 58',
    'why choose solar energy 59',
    'why choose solar energy 60',
    'why choose solar energy 61',
    'why choose solar energy 62',
    'why choose solar energy 63',
    'why choose solar energy 64',
    'why choose solar energy 65',
    'why choose solar energy 66',
    'why choose solar energy 67',
    'why choose solar energy 68',
    'why choose solar energy 69',
    'why choose solar energy 70',
    'why choose solar energy 71',
    'why choose solar energy 72',
    'why choose solar energy 73',
    'why choose solar energy 74',
    'why choose solar energy 75',
    'why choose solar energy 76',
    'why choose solar energy 77',
    'why choose solar energy 78',
    'why choose solar energy 79',
    'why choose solar energy 80',
    'why choose solar energy 81',
    'why choose solar energy 82',
    'why choose solar energy 83',
    'why choose solar energy 84',
    'why choose solar energy 85',
    'why choose solar energy 86',
    'why choose solar energy 87',
    'why choose solar energy 88',
    'why choose solar energy 89',
    'why choose solar energy 90',
    'why choose solar energy 91',
    'why choose solar energy 92',
    'why choose solar energy 93',
    'why choose solar energy 94',
    'why choose solar energy 95',
    'why choose solar energy 96',
    'why choose solar energy 97',
    'why choose solar energy 98',
    'why choose solar energy 99',
    'solar benefits 0',
    'solar benefits 1',
    'solar benefits 2',
    'solar benefits 3',
    'solar benefits 4',
    'solar benefits 5',
    'solar benefits 6',
    'solar benefits 7',
    'solar benefits 8',
    'solar benefits 9',
    'solar benefits 10',
    'solar benefits 11',
    'solar benefits 12',
    'solar benefits 13',
    'solar benefits 14',
    'solar benefits 15',
    'solar benefits 16',
    'solar benefits 17',
    'solar benefits 18',
    'solar benefits 19',
    'solar benefits 20',
    'solar benefits 21',
    'solar benefits 22',
    'solar benefits 23',
    'solar benefits 24',
    'solar benefits 25',
    'solar benefits 26',
    'solar benefits 27',
    'solar benefits 28',
    'solar benefits 29',
    'solar benefits 30',
    'solar benefits 31',
    'solar benefits 32',
    'solar benefits 33',
    'solar benefits 34',
    'solar benefits 35',
    'solar benefits 36',
    'solar benefits 37',
    'solar benefits 38',
    'solar benefits 39',
    'solar benefits 40',
    'solar benefits 41',
    'solar benefits 42',
    'solar benefits 43',
    'solar benefits 44',
    'solar benefits 45',
    'solar benefits 46',
    'solar benefits 47',
    'solar benefits 48',
    'solar benefits 49',
    'solar benefits 50',
    'solar benefits 51',
    'solar benefits 52',
    'solar benefits 53',
    'solar benefits 54',
    'solar benefits 55',
    'solar benefits 56',
    'solar benefits 57',
    'solar benefits 58',
    'solar benefits 59',
    'solar benefits 60',
    'solar benefits 61',
    'solar benefits 62',
    'solar benefits 63',
    'solar benefits 64',
    'solar benefits 65',
    'solar benefits 66',
    'solar benefits 67',
    'solar benefits 68',
    'solar benefits 69',
    'solar benefits 70',
    'solar benefits 71',
    'solar benefits 72',
    'solar benefits 73',
    'solar benefits 74',
    'solar benefits 75',
    'solar benefits 76',
    'solar benefits 77',
    'solar benefits 78',
    'solar benefits 79',
    'solar benefits 80',
    'solar benefits 81',
    'solar benefits 82',
    'solar benefits 83',
    'solar benefits 84',
    'solar benefits 85',
    'solar benefits 86',
    'solar benefits 87',
    'solar benefits 88',
    'solar benefits 89',
    'solar benefits 90',
    'solar benefits 91',
    'solar benefits 92',
    'solar benefits 93',
    'solar benefits 94',
    'solar benefits 95',
    'solar benefits 96',
    'solar benefits 97',
    'solar benefits 98',
    'solar benefits 99',
    'reduce electricity bill 0',
    'reduce electricity bill 1',
    'reduce electricity bill 2',
    'reduce electricity bill 3',
    'reduce electricity bill 4',
    'reduce electricity bill 5',
    'reduce electricity bill 6',
    'reduce electricity bill 7',
    'reduce electricity bill 8',
    'reduce electricity bill 9',
    'reduce electricity bill 10'
  ],
  authors: [{ name: 'BRL RENEWABLE ENERGIES PVT LTD' }],
  creator: 'BRL RENEWABLE ENERGIES PVT LTD',
  publisher: 'BRL RENEWABLE ENERGIES PVT LTD',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: 'About BRL RENEWABLE ENERGIES PVT LTD | Our Mission to Power India with Solar Energy',
    description: 'Learn about BRL RENEWABLE ENERGIES PVT LTD, a leading solar EPC company in India dedicated to providing high-quality, affordable solar energy solutions for a sustainable future.',
    url: 'https://makingindiagreen.in',
    siteName: 'BRL RENEWABLE ENERGIES PVT LTD',
    images: [
      {
        url: 'https://makingindiagreen.in/images/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'About BRL RENEWABLE ENERGIES PVT LTD | Our Mission to Power India with Solar Energy',
      },
    ],
    locale: 'en_IN',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'About BRL RENEWABLE ENERGIES PVT LTD | Our Mission to Power India with Solar Energy',
    description: 'Learn about BRL RENEWABLE ENERGIES PVT LTD, a leading solar EPC company in India dedicated to providing high-quality, affordable solar energy solutions for a sustainable future.',
    creator: '@abhisolar',
    images: ['https://makingindiagreen.in/images/twitter-image.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: 'https://makingindiagreen.in',
    languages: {
      'en-IN': 'https://makingindiagreen.in',
      'hi-IN': 'https://makingindiagreen.in/hi',
    },
  },
};
