import type { Metadata } from 'next';

export const gallerySeo: Metadata = {
  title: 'Our Solar Installations Gallery | Abhi Solar Projects',
  description: 'View our portfolio of successful solar installations across residential rooftops, commercial buildings, and industrial plants in India.',
  keywords: [
    'rooftop solar projects in Lucknow',
    'solar installation photos in Surat',
    'rooftop solar projects in Delhi NCR',
    'solar installation photos in Jaipur',
    'school solar plant case study',
    '3kW solar plant pictures',
    'solar installation photos in Bangalore',
    'solar installation photos in Lucknow',
    'home solar installation images',
    'office solar plant case study',
    'solar panel roof mount photos',
    'solar installation photos in Ahmedabad',
    'solar installation photos in Indore',
    'residential solar installation images',
    'solar installation photos in Chennai',
    'home solar plant case study',
    'commercial solar installation images',
    'hospital solar plant case study',
    '2kW solar plant pictures',
    'rooftop solar projects in Ahmedabad',
    'rooftop solar projects in Jaipur',
    'rooftop solar projects in Hyderabad',
    '5kW solar plant pictures',
    '10kW solar plant pictures',
    '500kW solar plant pictures',
    'agriculture solar plant case study',
    'rooftop solar projects in Chennai',
    '50kW solar plant pictures',
    '20kW solar plant pictures',
    'industrial solar plant drone view',
    'rooftop solar projects in Mumbai',
    'industrial solar plant case study',
    '1kW solar plant pictures',
    '100kW solar plant pictures',
    'school solar installation images',
    'factory solar plant case study',
    'solar commercial projects showcase',
    'solar installation photos in Delhi NCR',
    'rooftop solar projects in Indore',
    'abhi solar gallery',
    'solar installation photos in Mumbai',
    'factory solar installation images',
    'rooftop solar projects in Nagpur',
    'rooftop solar projects in Pune',
    'solar successful installations',
    'solar installation photos in Pune',
    'agriculture solar installation images',
    'commercial solar plant case study',
    'rooftop solar projects in Surat',
    'solar project portfolio',
    'office solar installation images',
    'residential solar plant case study',
    'hospital solar installation images',
    'solar installation photos in Hyderabad',
    'solar installation photos in Nagpur',
    'industrial solar installation images',
    'rooftop solar projects in Bangalore',
    'why choose solar energy 0',
    'why choose solar energy 1',
    'why choose solar energy 2',
    'why choose solar energy 3',
    'why choose solar energy 4',
    'why choose solar energy 5',
    'why choose solar energy 6',
    'why choose solar energy 7',
    'why choose solar energy 8',
    'why choose solar energy 9',
    'why choose solar energy 10',
    'why choose solar energy 11',
    'why choose solar energy 12',
    'why choose solar energy 13',
    'why choose solar energy 14',
    'why choose solar energy 15',
    'why choose solar energy 16',
    'why choose solar energy 17',
    'why choose solar energy 18',
    'why choose solar energy 19',
    'why choose solar energy 20',
    'why choose solar energy 21',
    'why choose solar energy 22',
    'why choose solar energy 23',
    'why choose solar energy 24',
    'why choose solar energy 25',
    'why choose solar energy 26',
    'why choose solar energy 27',
    'why choose solar energy 28',
    'why choose solar energy 29',
    'why choose solar energy 30',
    'why choose solar energy 31',
    'why choose solar energy 32',
    'why choose solar energy 33',
    'why choose solar energy 34',
    'why choose solar energy 35',
    'why choose solar energy 36',
    'why choose solar energy 37',
    'why choose solar energy 38',
    'why choose solar energy 39',
    'why choose solar energy 40',
    'why choose solar energy 41',
    'why choose solar energy 42',
    'why choose solar energy 43',
    'why choose solar energy 44',
    'why choose solar energy 45',
    'why choose solar energy 46',
    'why choose solar energy 47',
    'why choose solar energy 48',
    'why choose solar energy 49',
    'why choose solar energy 50',
    'why choose solar energy 51',
    'why choose solar energy 52',
    'why choose solar energy 53',
    'why choose solar energy 54',
    'why choose solar energy 55',
    'why choose solar energy 56',
    'why choose solar energy 57',
    'why choose solar energy 58',
    'why choose solar energy 59',
    'why choose solar energy 60',
    'why choose solar energy 61',
    'why choose solar energy 62',
    'why choose solar energy 63',
    'why choose solar energy 64',
    'why choose solar energy 65',
    'why choose solar energy 66',
    'why choose solar energy 67',
    'why choose solar energy 68',
    'why choose solar energy 69',
    'why choose solar energy 70',
    'why choose solar energy 71',
    'why choose solar energy 72',
    'why choose solar energy 73',
    'why choose solar energy 74',
    'why choose solar energy 75',
    'why choose solar energy 76',
    'why choose solar energy 77',
    'why choose solar energy 78',
    'why choose solar energy 79',
    'why choose solar energy 80',
    'why choose solar energy 81',
    'why choose solar energy 82',
    'why choose solar energy 83',
    'why choose solar energy 84',
    'why choose solar energy 85',
    'why choose solar energy 86',
    'why choose solar energy 87',
    'why choose solar energy 88',
    'why choose solar energy 89',
    'why choose solar energy 90',
    'why choose solar energy 91',
    'why choose solar energy 92',
    'why choose solar energy 93',
    'why choose solar energy 94',
    'why choose solar energy 95',
    'why choose solar energy 96',
    'why choose solar energy 97',
    'why choose solar energy 98',
    'why choose solar energy 99',
    'solar benefits 0',
    'solar benefits 1',
    'solar benefits 2',
    'solar benefits 3',
    'solar benefits 4',
    'solar benefits 5',
    'solar benefits 6',
    'solar benefits 7',
    'solar benefits 8',
    'solar benefits 9',
    'solar benefits 10',
    'solar benefits 11',
    'solar benefits 12',
    'solar benefits 13',
    'solar benefits 14',
    'solar benefits 15',
    'solar benefits 16',
    'solar benefits 17',
    'solar benefits 18',
    'solar benefits 19',
    'solar benefits 20',
    'solar benefits 21',
    'solar benefits 22',
    'solar benefits 23',
    'solar benefits 24',
    'solar benefits 25',
    'solar benefits 26',
    'solar benefits 27',
    'solar benefits 28',
    'solar benefits 29',
    'solar benefits 30',
    'solar benefits 31',
    'solar benefits 32',
    'solar benefits 33',
    'solar benefits 34',
    'solar benefits 35',
    'solar benefits 36',
    'solar benefits 37',
    'solar benefits 38',
    'solar benefits 39',
    'solar benefits 40',
    'solar benefits 41',
    'solar benefits 42',
    'solar benefits 43',
    'solar benefits 44',
    'solar benefits 45',
    'solar benefits 46',
    'solar benefits 47',
    'solar benefits 48',
    'solar benefits 49',
    'solar benefits 50',
    'solar benefits 51',
    'solar benefits 52',
    'solar benefits 53',
    'solar benefits 54',
    'solar benefits 55',
    'solar benefits 56',
    'solar benefits 57',
    'solar benefits 58',
    'solar benefits 59',
    'solar benefits 60',
    'solar benefits 61',
    'solar benefits 62',
    'solar benefits 63',
    'solar benefits 64',
    'solar benefits 65',
    'solar benefits 66',
    'solar benefits 67',
    'solar benefits 68',
    'solar benefits 69',
    'solar benefits 70',
    'solar benefits 71',
    'solar benefits 72',
    'solar benefits 73',
    'solar benefits 74',
    'solar benefits 75',
    'solar benefits 76',
    'solar benefits 77',
    'solar benefits 78',
    'solar benefits 79',
    'solar benefits 80',
    'solar benefits 81',
    'solar benefits 82',
    'solar benefits 83',
    'solar benefits 84',
    'solar benefits 85',
    'solar benefits 86',
    'solar benefits 87',
    'solar benefits 88',
    'solar benefits 89',
    'solar benefits 90',
    'solar benefits 91',
    'solar benefits 92',
    'solar benefits 93',
    'solar benefits 94',
    'solar benefits 95',
    'solar benefits 96',
    'solar benefits 97',
    'solar benefits 98',
    'solar benefits 99',
    'reduce electricity bill 0',
    'reduce electricity bill 1',
    'reduce electricity bill 2',
    'reduce electricity bill 3',
    'reduce electricity bill 4',
    'reduce electricity bill 5',
    'reduce electricity bill 6',
    'reduce electricity bill 7',
    'reduce electricity bill 8',
    'reduce electricity bill 9',
    'reduce electricity bill 10',
    'reduce electricity bill 11',
    'reduce electricity bill 12'
  ],
  authors: [{ name: 'Abhi Solar' }],
  creator: 'Abhi Solar',
  publisher: 'Abhi Solar',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: 'Our Solar Installations Gallery | Abhi Solar Projects',
    description: 'View our portfolio of successful solar installations across residential rooftops, commercial buildings, and industrial plants in India.',
    url: 'https://makingindiagreen.in',
    siteName: 'Abhi Solar',
    images: [
      {
        url: 'https://makingindiagreen.in/images/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'Our Solar Installations Gallery | Abhi Solar Projects',
      },
    ],
    locale: 'en_IN',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Our Solar Installations Gallery | Abhi Solar Projects',
    description: 'View our portfolio of successful solar installations across residential rooftops, commercial buildings, and industrial plants in India.',
    creator: '@abhisolar',
    images: ['https://makingindiagreen.in/images/twitter-image.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: 'https://makingindiagreen.in',
    languages: {
      'en-IN': 'https://makingindiagreen.in',
      'hi-IN': 'https://makingindiagreen.in/hi',
    },
  },
};
