import type { Metadata } from 'next';

export const homeSeo: Metadata = {
  title: 'Top Solar EPC Company in India | Residential & Commercial Solar | Abhi Solar',
  description: 'Abhi Solar provides the best solar energy solutions across India. Save up to 90% on electricity bills with our rooftop solar panels for home, office, and factory.',
  keywords: [
    'rooftop solar installation in Ahmedabad',
    '20kW rooftop solar price in india',
    '500kW off grid solar price in india',
    'best solar company in Pune',
    '20kW solar system price in india',
    'buy rooftop solar online',
    '50kW solar inverter price in india',
    'electricity bill reduction for agriculture using solar',
    'electricity bill reduction for commercial using solar',
    '20kW off grid solar price in india',
    'electricity bill reduction for office using solar',
    'solar subsidy in Tamil Nadu',
    'rooftop solar installation in Jaipur',
    '100kW on grid solar price in india',
    '500kW solar battery price in india',
    'monocrystalline solar panels',
    'best solar company in Bangalore',
    '2kW solar battery price in india',
    '10kW rooftop solar price in india',
    '20kW solar panel price in india',
    'best solar company in Delhi NCR',
    '1kW solar inverter price in india',
    'rooftop solar installation in Chennai',
    '100kW solar system price in india',
    '10kW hybrid solar price in india',
    'solar subsidy in Delhi',
    'buy solar panel online',
    '3kW rooftop solar price in india',
    '50kW solar battery price in india',
    '50kW off grid solar price in india',
    'buy off grid solar online',
    '100kW hybrid solar price in india',
    'buy hybrid solar online',
    'buy solar system online',
    'solar energy for school',
    'solar subsidy in Telangana',
    '500kW solar panel price in india',
    '20kW on grid solar price in india',
    '1kW solar system price in india',
    'buy solar inverter online',
    'solar energy for office',
    '3kW on grid solar price in india',
    '2kW on grid solar price in india',
    'net metering application',
    'best solar company in Ahmedabad',
    '100kW solar battery price in india',
    '2kW solar inverter price in india',
    'solar panel warranty',
    'electricity bill reduction for factory using solar',
    '5kW solar panel price in india',
    'solar panels in MP',
    'rooftop solar installation in Indore',
    '10kW solar panel price in india',
    'solar panels in Rajasthan',
    'rooftop solar installation in Delhi NCR',
    'solar energy for factory',
    'solar subsidy in Rajasthan',
    'solar subsidy in UP',
    '3kW off grid solar price in india',
    'rooftop solar installation in Hyderabad',
    '100kW solar inverter price in india',
    'electricity bill reduction for hospital using solar',
    'electricity bill reduction for school using solar',
    '2kW solar panel price in india',
    '100kW rooftop solar price in india',
    'bifacial solar panels',
    'zero cost emi solar',
    '100kW solar panel price in india',
    '1kW rooftop solar price in india',
    '1kW solar panel price in india',
    '5kW solar inverter price in india',
    '10kW solar battery price in india',
    'solar panels in Haryana',
    '1kW on grid solar price in india',
    'solar subsidy in Gujarat',
    '50kW on grid solar price in india',
    'solar energy for residential',
    '1kW solar battery price in india',
    'solar power plant',
    'solar energy for commercial',
    'free electricity scheme solar',
    '3kW hybrid solar price in india',
    'solar energy for hospital',
    'solar panels in UP',
    '5kW hybrid solar price in india',
    '10kW off grid solar price in india',
    'electricity bill reduction for home using solar',
    '20kW solar inverter price in india',
    'solar loan',
    'solar panels in Gujarat',
    'pm surya ghar yojana',
    'rooftop solar installation in Nagpur',
    'solar panels in Telangana',
    '5kW on grid solar price in india',
    'solar subsidy in Maharashtra',
    '5kW solar battery price in india',
    '500kW hybrid solar price in india',
    'best solar company in Jaipur',
    '20kW hybrid solar price in india',
    '100kW off grid solar price in india',
    '10kW on grid solar price in india',
    'best solar company in Indore',
    'rooftop solar installation in Pune',
    '1kW off grid solar price in india',
    '1kW hybrid solar price in india',
    '500kW on grid solar price in india',
    '50kW solar panel price in india',
    '3kW solar system price in india',
    '2kW off grid solar price in india',
    '3kW solar battery price in india',
    '2kW hybrid solar price in india',
    'solar panels in Punjab',
    'solar energy for industrial',
    'electricity bill reduction for industrial using solar',
    '500kW solar system price in india',
    'buy solar battery online',
    'electricity bill reduction for residential using solar',
    'rooftop solar installation in Mumbai',
    '20kW solar battery price in india',
    '10kW solar system price in india',
    '2kW rooftop solar price in india',
    '500kW rooftop solar price in india',
    'solar panels in Delhi',
    'rooftop solar installation in Bangalore',
    'best solar company in Chennai',
    '50kW hybrid solar price in india',
    'best solar company in Lucknow',
    '2kW solar system price in india',
    'solar subsidy in Kerala',
    'rooftop solar installation in Lucknow',
    '500kW solar inverter price in india',
    '5kW rooftop solar price in india',
    '10kW solar inverter price in india',
    'rooftop solar installation in Surat',
    '3kW solar inverter price in india',
    'solar subsidy in MP',
    '50kW solar system price in india',
    'solar energy for agriculture',
    'solar panels in Maharashtra',
    'solar panels in Karnataka',
    'solar subsidy in Punjab',
    '5kW solar system price in india',
    '3kW solar panel price in india',
    '5kW off grid solar price in india',
    'solar panel lifespan',
    'buy on grid solar online',
    'best solar company in Mumbai',
    'solar emi options',
    'solar panels in Tamil Nadu',
    'best solar company in Surat',
    'best solar company in Hyderabad',
    '50kW rooftop solar price in india',
    'solar subsidy in Karnataka',
    'solar energy for home',
    'solar subsidy in Haryana',
    'solar panels in Kerala',
    'best solar company in Nagpur',
    'why choose solar energy 0',
    'why choose solar energy 1',
    'why choose solar energy 2',
    'why choose solar energy 3',
    'why choose solar energy 4',
    'why choose solar energy 5',
    'why choose solar energy 6',
    'why choose solar energy 7',
    'why choose solar energy 8',
    'why choose solar energy 9',
    'why choose solar energy 10',
    'why choose solar energy 11',
    'why choose solar energy 12',
    'why choose solar energy 13',
    'why choose solar energy 14',
    'why choose solar energy 15',
    'why choose solar energy 16',
    'why choose solar energy 17',
    'why choose solar energy 18',
    'why choose solar energy 19',
    'why choose solar energy 20',
    'why choose solar energy 21',
    'why choose solar energy 22',
    'why choose solar energy 23',
    'why choose solar energy 24',
    'why choose solar energy 25',
    'why choose solar energy 26',
    'why choose solar energy 27',
    'why choose solar energy 28',
    'why choose solar energy 29',
    'why choose solar energy 30',
    'why choose solar energy 31',
    'why choose solar energy 32',
    'why choose solar energy 33',
    'why choose solar energy 34',
    'why choose solar energy 35',
    'why choose solar energy 36',
    'why choose solar energy 37',
    'why choose solar energy 38',
    'why choose solar energy 39',
    'why choose solar energy 40',
    'why choose solar energy 41',
    'why choose solar energy 42',
    'why choose solar energy 43',
    'why choose solar energy 44',
    'why choose solar energy 45',
    'why choose solar energy 46',
    'why choose solar energy 47',
    'why choose solar energy 48',
    'why choose solar energy 49',
    'why choose solar energy 50',
    'why choose solar energy 51',
    'why choose solar energy 52',
    'why choose solar energy 53',
    'why choose solar energy 54',
    'why choose solar energy 55',
    'why choose solar energy 56',
    'why choose solar energy 57',
    'why choose solar energy 58',
    'why choose solar energy 59',
    'why choose solar energy 60',
    'why choose solar energy 61',
    'why choose solar energy 62',
    'why choose solar energy 63',
    'why choose solar energy 64',
    'why choose solar energy 65',
    'why choose solar energy 66',
    'why choose solar energy 67',
    'why choose solar energy 68',
    'why choose solar energy 69',
    'why choose solar energy 70',
    'why choose solar energy 71',
    'why choose solar energy 72',
    'why choose solar energy 73',
    'why choose solar energy 74',
    'why choose solar energy 75',
    'why choose solar energy 76',
    'why choose solar energy 77',
    'why choose solar energy 78',
    'why choose solar energy 79',
    'why choose solar energy 80',
    'why choose solar energy 81',
    'why choose solar energy 82',
    'why choose solar energy 83',
    'why choose solar energy 84',
    'why choose solar energy 85',
    'why choose solar energy 86',
    'why choose solar energy 87',
    'why choose solar energy 88',
    'why choose solar energy 89',
    'why choose solar energy 90',
    'why choose solar energy 91',
    'why choose solar energy 92',
    'why choose solar energy 93',
    'why choose solar energy 94',
    'why choose solar energy 95',
    'why choose solar energy 96',
    'why choose solar energy 97',
    'why choose solar energy 98',
    'why choose solar energy 99',
    'solar benefits 0',
    'solar benefits 1',
    'solar benefits 2',
    'solar benefits 3',
    'solar benefits 4',
    'solar benefits 5',
    'solar benefits 6',
    'solar benefits 7',
    'solar benefits 8',
    'solar benefits 9',
    'solar benefits 10',
    'solar benefits 11',
    'solar benefits 12'
  ],
  authors: [{ name: 'Abhi Solar' }],
  creator: 'Abhi Solar',
  publisher: 'Abhi Solar',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: 'Top Solar EPC Company in India | Residential & Commercial Solar | Abhi Solar',
    description: 'Abhi Solar provides the best solar energy solutions across India. Save up to 90% on electricity bills with our rooftop solar panels for home, office, and factory.',
    url: 'https://makingindiagreen.in',
    siteName: 'Abhi Solar',
    images: [
      {
        url: 'https://makingindiagreen.in/images/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'Top Solar EPC Company in India | Residential & Commercial Solar | Abhi Solar',
      },
    ],
    locale: 'en_IN',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Top Solar EPC Company in India | Residential & Commercial Solar | Abhi Solar',
    description: 'Abhi Solar provides the best solar energy solutions across India. Save up to 90% on electricity bills with our rooftop solar panels for home, office, and factory.',
    creator: '@abhisolar',
    images: ['https://makingindiagreen.in/images/twitter-image.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: 'https://makingindiagreen.in',
    languages: {
      'en-IN': 'https://makingindiagreen.in',
      'hi-IN': 'https://makingindiagreen.in/hi',
    },
  },
};
