import type { Metadata } from 'next';
import { locationSeoData } from './locationdata';

export const serviceSeo: Metadata = {
  title: 'Solar Energy Services | Residential, Commercial & Industrial | BRL RENEWABLE ENERGIES PVT LTD',
  description: 'Explore our solar energy services including residential rooftop solar, commercial solar plants, industrial solar solutions, and PM-KUSUM agricultural solar pumps.',
  keywords: [
    ...(locationSeoData.keywords as string[]),
    'off grid solar for home',
    'solar inverter installation services for agriculture',
    'solar battery for factory',
    'hybrid solar installation services for commercial',
    'solar battery for agriculture',
    'solar system installation services for residential',
    'rooftop solar for agriculture',
    'solar system installation services for hospital',
    'rooftop solar for industrial',
    'solar panel for industrial',
    'solar panel installation services for hospital',
    'rooftop solar installation services for home',
    'solar inverter for residential',
    'solar battery repair and maintenance in Mumbai',
    'hybrid solar for commercial',
    'off grid solar for school',
    '500kW solar plant epc service',
    'hybrid solar repair and maintenance in Indore',
    'on grid solar for residential',
    'solar battery repair and maintenance in Indore',
    'solar panel installation services for home',
    'hybrid solar installation services for home',
    'hybrid solar repair and maintenance in Delhi NCR',
    'rooftop solar for office',
    'solar inverter installation services for residential',
    'on grid solar installation services for industrial',
    'solar panel repair and maintenance in Surat',
    'solar battery repair and maintenance in Pune',
    '100kW solar plant epc service',
    'solar panel repair and maintenance in Nagpur',
    'solar system installation services for commercial',
    'solar system repair and maintenance in Mumbai',
    'solar inverter installation services for industrial',
    'off grid solar for commercial',
    'hybrid solar for agriculture',
    'solar battery repair and maintenance in Surat',
    'rooftop solar installation services for school',
    'solar battery repair and maintenance in Ahmedabad',
    'off grid solar repair and maintenance in Surat',
    'off grid solar installation services for office',
    'off grid solar repair and maintenance in Jaipur',
    'hybrid solar for industrial',
    'on grid solar for industrial',
    'off grid solar for factory',
    'solar system for home',
    'rooftop solar for home',
    'off grid solar repair and maintenance in Ahmedabad',
    'solar panel installation services for office',
    'solar inverter for industrial',
    'solar panel repair and maintenance in Indore',
    'solar panel repair and maintenance in Ahmedabad',
    'rooftop solar repair and maintenance in Jaipur',
    'solar battery installation services for commercial',
    'solar system for commercial',
    'hybrid solar installation services for office',
    '10kW solar plant epc service',
    'off grid solar for office',
    'off grid solar installation services for home',
    'solar inverter repair and maintenance in Delhi NCR',
    'rooftop solar installation services for agriculture',
    'on grid solar for office',
    'solar inverter for factory',
    'on grid solar repair and maintenance in Indore',
    'hybrid solar repair and maintenance in Lucknow',
    'off grid solar repair and maintenance in Indore',
    'solar battery repair and maintenance in Delhi NCR',
    'solar inverter repair and maintenance in Hyderabad',
    'solar panel installation services for agriculture',
    'solar system installation services for school',
    'solar system for agriculture',
    'solar system installation services for office',
    'solar inverter repair and maintenance in Mumbai',
    'solar system installation services for factory',
    'rooftop solar installation services for commercial',
    'on grid solar installation services for factory',
    'solar inverter installation services for hospital',
    'hybrid solar installation services for industrial',
    'solar battery installation services for agriculture',
    'solar panel for school',
    'solar battery repair and maintenance in Lucknow',
    'on grid solar for agriculture',
    'solar inverter for office',
    'solar battery repair and maintenance in Bangalore',
    'rooftop solar repair and maintenance in Surat',
    'solar inverter repair and maintenance in Pune',
    'hybrid solar installation services for hospital',
    'solar inverter repair and maintenance in Jaipur',
    'rooftop solar repair and maintenance in Chennai',
    'off grid solar installation services for school',
    'solar inverter for school',
    'solar panel installation services for factory',
    'solar system for office',
    'solar system installation services for industrial',
    'off grid solar repair and maintenance in Hyderabad',
    'solar inverter for agriculture',
    'solar panel repair and maintenance in Lucknow',
    'rooftop solar repair and maintenance in Indore',
    'solar battery installation services for school',
    'solar system repair and maintenance in Chennai',
    'on grid solar installation services for agriculture',
    'solar battery for home',
    'solar battery installation services for office',
    'on grid solar installation services for home',
    'off grid solar for residential',
    'solar battery for industrial',
    'commercial solar epc',
    'on grid solar repair and maintenance in Ahmedabad',
    'solar panel repair and maintenance in Chennai',
    'solar system repair and maintenance in Lucknow',
    'solar battery installation services for residential',
    'solar battery installation services for factory',
    'on grid solar repair and maintenance in Surat',
    'solar battery for residential',
    'solar battery installation services for home',
    'solar panel repair and maintenance in Mumbai',
    'solar inverter repair and maintenance in Bangalore',
    'solar battery installation services for industrial',
    'on grid solar for school',
    '5kW solar plant epc service',
    'solar panel repair and maintenance in Hyderabad',
    'solar inverter installation services for office',
    'solar system repair and maintenance in Bangalore',
    'hybrid solar for school',
    'rooftop solar for school',
    'rooftop solar for residential',
    'solar system for residential',
    'rooftop solar repair and maintenance in Delhi NCR',
    'on grid solar repair and maintenance in Hyderabad',
    'off grid solar repair and maintenance in Pune',
    'hybrid solar for home',
    'solar system installation services for home',
    'solar system installation services for agriculture',
    'on grid solar repair and maintenance in Chennai',
    'solar plant shadow analysis',
    'on grid solar for home',
    'solar battery repair and maintenance in Nagpur',
    'on grid solar installation services for commercial',
    'solar battery repair and maintenance in Chennai',
    'solar net metering installation',
    'solar system repair and maintenance in Delhi NCR',
    'solar inverter for hospital',
    'solar system repair and maintenance in Indore',
    'solar panel for agriculture',
    'solar system for school',
    'solar battery repair and maintenance in Jaipur',
    'on grid solar for commercial',
    'solar system repair and maintenance in Ahmedabad',
    'solar inverter for commercial',
    'solar battery for commercial',
    'on grid solar repair and maintenance in Delhi NCR',
    'off grid solar installation services for commercial',
    'rooftop solar repair and maintenance in Lucknow',
    'solar panel repair and maintenance in Pune',
    'hybrid solar repair and maintenance in Pune',
    'off grid solar repair and maintenance in Delhi NCR',
    'hybrid solar for residential',
    'solar panel repair and maintenance in Bangalore',
    'solar panel installation services for commercial',
    'hybrid solar installation services for agriculture',
    'rooftop solar repair and maintenance in Mumbai',
    'hybrid solar repair and maintenance in Jaipur',
    'solar battery for hospital',
    'solar battery for school',
    'solar plant commissioning',
    'solar panel for factory',
    'solar panel installation services for school',
    'rooftop solar repair and maintenance in Ahmedabad',
    'hybrid solar repair and maintenance in Hyderabad',
    'off grid solar repair and maintenance in Mumbai',
    'solar system repair and maintenance in Nagpur',
    'hybrid solar for hospital',
    'hybrid solar installation services for school',
    'solar system for hospital',
    'rooftop solar for hospital',
    'on grid solar installation services for office',
    'solar system repair and maintenance in Pune',
    'solar inverter repair and maintenance in Ahmedabad',
    'solar system repair and maintenance in Surat',
    'on grid solar for hospital',
    'solar panel for home',
    'solar inverter repair and maintenance in Surat',
    'solar inverter for home',
    'off grid solar installation services for factory',
    'solar panel installation services for industrial',
    'solar structure design',
    'rooftop solar installation services for factory',
    'solar inverter installation services for school',
    'rooftop solar installation services for industrial',
    'off grid solar installation services for residential',
    '1kW solar plant epc service',
    'solar system health checkup',
    'solar panel installation services for residential',
    'solar system repair and maintenance in Hyderabad',
    'off grid solar repair and maintenance in Chennai',
    'hybrid solar for factory',
    'solar battery installation services for hospital',
    'solar inverter repair and maintenance in Indore',
    'off grid solar installation services for agriculture',
    'off grid solar repair and maintenance in Nagpur',
    '3kW solar plant epc service',
    'hybrid solar installation services for factory',
    'solar panel for hospital',
    'off grid solar for hospital',
    'solar battery for office',
    'solar panel for residential',
    'solar system for factory',
    'solar inverter installation services for home',
    'off grid solar installation services for industrial',
    'solar inverter repair and maintenance in Nagpur',
    '2kW solar plant epc service',
    'rooftop solar for commercial',
    'off grid solar for agriculture',
    'off grid solar repair and maintenance in Bangalore',
    'hybrid solar for office',
    'on grid solar repair and maintenance in Pune',
    'on grid solar repair and maintenance in Mumbai',
    'off grid solar for industrial',
    'rooftop solar repair and maintenance in Hyderabad',
    'solar battery repair and maintenance in Hyderabad',
    'solar inverter repair and maintenance in Lucknow',
    'solar panel for office',
    'rooftop solar repair and maintenance in Nagpur',
    'on grid solar installation services for residential',
    'hybrid solar repair and maintenance in Bangalore',
    'off grid solar installation services for hospital',
    'on grid solar repair and maintenance in Jaipur',
    'hybrid solar repair and maintenance in Surat',
    'solar system for industrial',
    'rooftop solar installation services for residential',
    'rooftop solar repair and maintenance in Bangalore',
    'solar inverter installation services for factory',
    'rooftop solar installation services for office',
    'solar inverter repair and maintenance in Chennai',
    'on grid solar repair and maintenance in Bangalore',
    'rooftop solar for factory',
    '20kW solar plant epc service',
    'on grid solar installation services for hospital',
    'solar panel repair and maintenance in Delhi NCR',
    'solar system repair and maintenance in Jaipur',
    'hybrid solar repair and maintenance in Mumbai',
    'solar panel for commercial',
    'hybrid solar repair and maintenance in Ahmedabad',
    'solar panel cleaning service',
    'solar panel repair and maintenance in Jaipur',
    'solar inverter installation services for commercial',
    'on grid solar installation services for school',
    'on grid solar repair and maintenance in Nagpur',
    'off grid solar repair and maintenance in Lucknow',
    'hybrid solar repair and maintenance in Chennai',
    'on grid solar for factory',
    'hybrid solar installation services for residential',
    'on grid solar repair and maintenance in Lucknow',
    'hybrid solar repair and maintenance in Nagpur',
    'solar amc',
    'rooftop solar repair and maintenance in Pune',
    'industrial solar epc',
    'rooftop solar installation services for hospital',
    '50kW solar plant epc service',
    'why choose solar energy 0',
    'why choose solar energy 1',
    'why choose solar energy 2',
    'why choose solar energy 3',
    'why choose solar energy 4',
    'why choose solar energy 5',
    'why choose solar energy 6',
    'why choose solar energy 7',
    'why choose solar energy 8',
    'why choose solar energy 9',
    'why choose solar energy 10',
    'why choose solar energy 11'
  ],
  authors: [{ name: 'BRL RENEWABLE ENERGIES PVT LTD' }],
  creator: 'BRL RENEWABLE ENERGIES PVT LTD',
  publisher: 'BRL RENEWABLE ENERGIES PVT LTD',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: 'Solar Energy Services | Residential, Commercial & Industrial | BRL RENEWABLE ENERGIES PVT LTD',
    description: 'Explore our solar energy services including residential rooftop solar, commercial solar plants, industrial solar solutions, and PM-KUSUM agricultural solar pumps.',
    url: 'https://makingindiagreen.in',
    siteName: 'BRL RENEWABLE ENERGIES PVT LTD',
    images: [
      {
        url: 'https://makingindiagreen.in/images/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'Solar Energy Services | Residential, Commercial & Industrial | BRL RENEWABLE ENERGIES PVT LTD',
      },
    ],
    locale: 'en_IN',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Solar Energy Services | Residential, Commercial & Industrial | BRL RENEWABLE ENERGIES PVT LTD',
    description: 'Explore our solar energy services including residential rooftop solar, commercial solar plants, industrial solar solutions, and PM-KUSUM agricultural solar pumps.',
    creator: '@abhisolar',
    images: ['https://makingindiagreen.in/images/twitter-image.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: 'https://makingindiagreen.in',
    languages: {
      'en-IN': 'https://makingindiagreen.in',
      'hi-IN': 'https://makingindiagreen.in/hi',
    },
  },
};
